python early_fusion.py --ss --modal t --pmode 0 --seed 0  --save_results
python early_fusion.py --ss --modal a --pmode 0 --seed 0  --save_results
python early_fusion.py --ss --modal v --pmode 0 --seed 0  --save_results
python early_fusion.py --ss --modal ta --pmode 0 --seed 0  --save_results
python early_fusion.py --ss --modal tv --pmode 0 --seed 0  --save_results
python early_fusion.py --ss --modal av --pmode 0 --seed 0  --save_results
python early_fusion.py --ss --modal tav --pmode 0 --seed 0  --save_results
python early_fusion.py --ss --modal t --pmode 1 --seed 0  --save_results
python early_fusion.py --ss --modal a --pmode 1 --seed 0  --save_results
python early_fusion.py --ss --modal v --pmode 1 --seed 0  --save_results
python early_fusion.py --ss --modal ta --pmode 1 --seed 0  --save_results
python early_fusion.py --ss --modal tv --pmode 1 --seed 0  --save_results
python early_fusion.py --ss --modal av --pmode 1 --seed 0  --save_results
python early_fusion.py --ss --modal tav --pmode 1 --seed 0  --save_results
python early_fusion.py --ss --modal t --pmode 2 --seed 0  --save_results
python early_fusion.py --ss --modal a --pmode 2 --seed 0  --save_results
python early_fusion.py --ss --modal v --pmode 2 --seed 0  --save_results
python early_fusion.py --ss --modal ta --pmode 2 --seed 0  --save_results
python early_fusion.py --ss --modal tv --pmode 2 --seed 0  --save_results
python early_fusion.py --ss --modal av --pmode 2 --seed 0  --save_results
python early_fusion.py --ss --modal tav --pmode 2 --seed 0  --save_results
python early_fusion.py --ss --modal t --pmode 3 --seed 0  --save_results
python early_fusion.py --ss --modal a --pmode 3 --seed 0  --save_results
python early_fusion.py --ss --modal v --pmode 3 --seed 0  --save_results
python early_fusion.py --ss --modal ta --pmode 3 --seed 0  --save_results
python early_fusion.py --ss --modal tv --pmode 3 --seed 0  --save_results
python early_fusion.py --ss --modal av --pmode 3 --seed 0  --save_results
python early_fusion.py --ss --modal tav --pmode 3 --seed 0  --save_results
python early_fusion.py --ss --modal t --pmode 4 --seed 0  --save_results
python early_fusion.py --ss --modal a --pmode 4 --seed 0  --save_results
python early_fusion.py --ss --modal v --pmode 4 --seed 0  --save_results
python early_fusion.py --ss --modal ta --pmode 4 --seed 0  --save_results
python early_fusion.py --ss --modal tv --pmode 4 --seed 0  --save_results
python early_fusion.py --ss --modal av --pmode 4 --seed 0  --save_results
python early_fusion.py --ss --modal tav --pmode 4 --seed 0  --save_results
python early_fusion.py --ss --modal t --pmode 5 --seed 0  --save_results
python early_fusion.py --ss --modal a --pmode 5 --seed 0  --save_results
python early_fusion.py --ss --modal v --pmode 5 --seed 0  --save_results
python early_fusion.py --ss --modal ta --pmode 5 --seed 0  --save_results
python early_fusion.py --ss --modal tv --pmode 5 --seed 0  --save_results
python early_fusion.py --ss --modal av --pmode 5 --seed 0  --save_results
python early_fusion.py --ss --modal tav --pmode 5 --seed 0  --save_results
python early_fusion.py --ss --modal t --pmode 6 --seed 0  --save_results
python early_fusion.py --ss --modal a --pmode 6 --seed 0  --save_results
python early_fusion.py --ss --modal v --pmode 6 --seed 0  --save_results
python early_fusion.py --ss --modal ta --pmode 6 --seed 0  --save_results
python early_fusion.py --ss --modal tv --pmode 6 --seed 0  --save_results
python early_fusion.py --ss --modal av --pmode 6 --seed 0  --save_results
python early_fusion.py --ss --modal tav --pmode 6 --seed 0  --save_results
python early_fusion.py --ss --modal t --pmode 7 --seed 0  --save_results
python early_fusion.py --ss --modal a --pmode 7 --seed 0  --save_results
python early_fusion.py --ss --modal v --pmode 7 --seed 0  --save_results
python early_fusion.py --ss --modal ta --pmode 7 --seed 0  --save_results
python early_fusion.py --ss --modal tv --pmode 7 --seed 0  --save_results
python early_fusion.py --ss --modal av --pmode 7 --seed 0  --save_results
python early_fusion.py --ss --modal tav --pmode 7 --seed 0  --save_results
python early_fusion.py --ss --modal t --pmode 8 --seed 0  --save_results
python early_fusion.py --ss --modal a --pmode 8 --seed 0  --save_results
python early_fusion.py --ss --modal v --pmode 8 --seed 0  --save_results
python early_fusion.py --ss --modal ta --pmode 8 --seed 0  --save_results
python early_fusion.py --ss --modal tv --pmode 8 --seed 0  --save_results
python early_fusion.py --ss --modal av --pmode 8 --seed 0  --save_results
python early_fusion.py --ss --modal tav --pmode 8 --seed 0  --save_results
python early_fusion.py --ss --modal t --pmode 0 --seed 1  --save_results
python early_fusion.py --ss --modal a --pmode 0 --seed 1  --save_results
python early_fusion.py --ss --modal v --pmode 0 --seed 1  --save_results
python early_fusion.py --ss --modal ta --pmode 0 --seed 1  --save_results
python early_fusion.py --ss --modal tv --pmode 0 --seed 1  --save_results
python early_fusion.py --ss --modal av --pmode 0 --seed 1  --save_results
python early_fusion.py --ss --modal tav --pmode 0 --seed 1  --save_results
python early_fusion.py --ss --modal t --pmode 1 --seed 1  --save_results
python early_fusion.py --ss --modal a --pmode 1 --seed 1  --save_results
python early_fusion.py --ss --modal v --pmode 1 --seed 1  --save_results
python early_fusion.py --ss --modal ta --pmode 1 --seed 1  --save_results
python early_fusion.py --ss --modal tv --pmode 1 --seed 1  --save_results
python early_fusion.py --ss --modal av --pmode 1 --seed 1  --save_results
python early_fusion.py --ss --modal tav --pmode 1 --seed 1  --save_results
python early_fusion.py --ss --modal t --pmode 2 --seed 1  --save_results
python early_fusion.py --ss --modal a --pmode 2 --seed 1  --save_results
python early_fusion.py --ss --modal v --pmode 2 --seed 1  --save_results
python early_fusion.py --ss --modal ta --pmode 2 --seed 1  --save_results
python early_fusion.py --ss --modal tv --pmode 2 --seed 1  --save_results
python early_fusion.py --ss --modal av --pmode 2 --seed 1  --save_results
python early_fusion.py --ss --modal tav --pmode 2 --seed 1  --save_results
python early_fusion.py --ss --modal t --pmode 3 --seed 1  --save_results
python early_fusion.py --ss --modal a --pmode 3 --seed 1  --save_results
python early_fusion.py --ss --modal v --pmode 3 --seed 1  --save_results
python early_fusion.py --ss --modal ta --pmode 3 --seed 1  --save_results
python early_fusion.py --ss --modal tv --pmode 3 --seed 1  --save_results
python early_fusion.py --ss --modal av --pmode 3 --seed 1  --save_results
python early_fusion.py --ss --modal tav --pmode 3 --seed 1  --save_results
python early_fusion.py --ss --modal t --pmode 4 --seed 1  --save_results
python early_fusion.py --ss --modal a --pmode 4 --seed 1  --save_results
python early_fusion.py --ss --modal v --pmode 4 --seed 1  --save_results
python early_fusion.py --ss --modal ta --pmode 4 --seed 1  --save_results
python early_fusion.py --ss --modal tv --pmode 4 --seed 1  --save_results
python early_fusion.py --ss --modal av --pmode 4 --seed 1  --save_results
python early_fusion.py --ss --modal tav --pmode 4 --seed 1  --save_results
python early_fusion.py --ss --modal t --pmode 5 --seed 1  --save_results
python early_fusion.py --ss --modal a --pmode 5 --seed 1  --save_results
python early_fusion.py --ss --modal v --pmode 5 --seed 1  --save_results
python early_fusion.py --ss --modal ta --pmode 5 --seed 1  --save_results
python early_fusion.py --ss --modal tv --pmode 5 --seed 1  --save_results
python early_fusion.py --ss --modal av --pmode 5 --seed 1  --save_results
python early_fusion.py --ss --modal tav --pmode 5 --seed 1  --save_results
python early_fusion.py --ss --modal t --pmode 6 --seed 1  --save_results
python early_fusion.py --ss --modal a --pmode 6 --seed 1  --save_results
python early_fusion.py --ss --modal v --pmode 6 --seed 1  --save_results
python early_fusion.py --ss --modal ta --pmode 6 --seed 1  --save_results
python early_fusion.py --ss --modal tv --pmode 6 --seed 1  --save_results
python early_fusion.py --ss --modal av --pmode 6 --seed 1  --save_results
python early_fusion.py --ss --modal tav --pmode 6 --seed 1  --save_results
python early_fusion.py --ss --modal t --pmode 7 --seed 1  --save_results
python early_fusion.py --ss --modal a --pmode 7 --seed 1  --save_results
python early_fusion.py --ss --modal v --pmode 7 --seed 1  --save_results
python early_fusion.py --ss --modal ta --pmode 7 --seed 1  --save_results
python early_fusion.py --ss --modal tv --pmode 7 --seed 1  --save_results
python early_fusion.py --ss --modal av --pmode 7 --seed 1  --save_results
python early_fusion.py --ss --modal tav --pmode 7 --seed 1  --save_results
python early_fusion.py --ss --modal t --pmode 8 --seed 1  --save_results
python early_fusion.py --ss --modal a --pmode 8 --seed 1  --save_results
python early_fusion.py --ss --modal v --pmode 8 --seed 1  --save_results
python early_fusion.py --ss --modal ta --pmode 8 --seed 1  --save_results
python early_fusion.py --ss --modal tv --pmode 8 --seed 1  --save_results
python early_fusion.py --ss --modal av --pmode 8 --seed 1  --save_results
python early_fusion.py --ss --modal tav --pmode 8 --seed 1  --save_results
python early_fusion.py --ss --modal t --pmode 0 --seed 2  --save_results
python early_fusion.py --ss --modal a --pmode 0 --seed 2  --save_results
python early_fusion.py --ss --modal v --pmode 0 --seed 2  --save_results
python early_fusion.py --ss --modal ta --pmode 0 --seed 2  --save_results
python early_fusion.py --ss --modal tv --pmode 0 --seed 2  --save_results
python early_fusion.py --ss --modal av --pmode 0 --seed 2  --save_results
python early_fusion.py --ss --modal tav --pmode 0 --seed 2  --save_results
python early_fusion.py --ss --modal t --pmode 1 --seed 2  --save_results
python early_fusion.py --ss --modal a --pmode 1 --seed 2  --save_results
python early_fusion.py --ss --modal v --pmode 1 --seed 2  --save_results
python early_fusion.py --ss --modal ta --pmode 1 --seed 2  --save_results
python early_fusion.py --ss --modal tv --pmode 1 --seed 2  --save_results
python early_fusion.py --ss --modal av --pmode 1 --seed 2  --save_results
python early_fusion.py --ss --modal tav --pmode 1 --seed 2  --save_results
python early_fusion.py --ss --modal t --pmode 2 --seed 2  --save_results
python early_fusion.py --ss --modal a --pmode 2 --seed 2  --save_results
python early_fusion.py --ss --modal v --pmode 2 --seed 2  --save_results
python early_fusion.py --ss --modal ta --pmode 2 --seed 2  --save_results
python early_fusion.py --ss --modal tv --pmode 2 --seed 2  --save_results
python early_fusion.py --ss --modal av --pmode 2 --seed 2  --save_results
python early_fusion.py --ss --modal tav --pmode 2 --seed 2  --save_results
python early_fusion.py --ss --modal t --pmode 3 --seed 2  --save_results
python early_fusion.py --ss --modal a --pmode 3 --seed 2  --save_results
python early_fusion.py --ss --modal v --pmode 3 --seed 2  --save_results
python early_fusion.py --ss --modal ta --pmode 3 --seed 2  --save_results
python early_fusion.py --ss --modal tv --pmode 3 --seed 2  --save_results
python early_fusion.py --ss --modal av --pmode 3 --seed 2  --save_results
python early_fusion.py --ss --modal tav --pmode 3 --seed 2  --save_results
python early_fusion.py --ss --modal t --pmode 4 --seed 2  --save_results
python early_fusion.py --ss --modal a --pmode 4 --seed 2  --save_results
python early_fusion.py --ss --modal v --pmode 4 --seed 2  --save_results
python early_fusion.py --ss --modal ta --pmode 4 --seed 2  --save_results
python early_fusion.py --ss --modal tv --pmode 4 --seed 2  --save_results
python early_fusion.py --ss --modal av --pmode 4 --seed 2  --save_results
python early_fusion.py --ss --modal tav --pmode 4 --seed 2  --save_results
python early_fusion.py --ss --modal t --pmode 5 --seed 2  --save_results
python early_fusion.py --ss --modal a --pmode 5 --seed 2  --save_results
python early_fusion.py --ss --modal v --pmode 5 --seed 2  --save_results
python early_fusion.py --ss --modal ta --pmode 5 --seed 2  --save_results
python early_fusion.py --ss --modal tv --pmode 5 --seed 2  --save_results
python early_fusion.py --ss --modal av --pmode 5 --seed 2  --save_results
python early_fusion.py --ss --modal tav --pmode 5 --seed 2  --save_results
python early_fusion.py --ss --modal t --pmode 6 --seed 2  --save_results
python early_fusion.py --ss --modal a --pmode 6 --seed 2  --save_results
python early_fusion.py --ss --modal v --pmode 6 --seed 2  --save_results
python early_fusion.py --ss --modal ta --pmode 6 --seed 2  --save_results
python early_fusion.py --ss --modal tv --pmode 6 --seed 2  --save_results
python early_fusion.py --ss --modal av --pmode 6 --seed 2  --save_results
python early_fusion.py --ss --modal tav --pmode 6 --seed 2  --save_results
python early_fusion.py --ss --modal t --pmode 7 --seed 2  --save_results
python early_fusion.py --ss --modal a --pmode 7 --seed 2  --save_results
python early_fusion.py --ss --modal v --pmode 7 --seed 2  --save_results
python early_fusion.py --ss --modal ta --pmode 7 --seed 2  --save_results
python early_fusion.py --ss --modal tv --pmode 7 --seed 2  --save_results
python early_fusion.py --ss --modal av --pmode 7 --seed 2  --save_results
python early_fusion.py --ss --modal tav --pmode 7 --seed 2  --save_results
python early_fusion.py --ss --modal t --pmode 8 --seed 2  --save_results
python early_fusion.py --ss --modal a --pmode 8 --seed 2  --save_results
python early_fusion.py --ss --modal v --pmode 8 --seed 2  --save_results
python early_fusion.py --ss --modal ta --pmode 8 --seed 2  --save_results
python early_fusion.py --ss --modal tv --pmode 8 --seed 2  --save_results
python early_fusion.py --ss --modal av --pmode 8 --seed 2  --save_results
python early_fusion.py --ss --modal tav --pmode 8 --seed 2  --save_results
python early_fusion.py --ss --modal t --pmode 0 --seed 3  --save_results
python early_fusion.py --ss --modal a --pmode 0 --seed 3  --save_results
python early_fusion.py --ss --modal v --pmode 0 --seed 3  --save_results
python early_fusion.py --ss --modal ta --pmode 0 --seed 3  --save_results
python early_fusion.py --ss --modal tv --pmode 0 --seed 3  --save_results
python early_fusion.py --ss --modal av --pmode 0 --seed 3  --save_results
python early_fusion.py --ss --modal tav --pmode 0 --seed 3  --save_results
python early_fusion.py --ss --modal t --pmode 1 --seed 3  --save_results
python early_fusion.py --ss --modal a --pmode 1 --seed 3  --save_results
python early_fusion.py --ss --modal v --pmode 1 --seed 3  --save_results
python early_fusion.py --ss --modal ta --pmode 1 --seed 3  --save_results
python early_fusion.py --ss --modal tv --pmode 1 --seed 3  --save_results
python early_fusion.py --ss --modal av --pmode 1 --seed 3  --save_results
python early_fusion.py --ss --modal tav --pmode 1 --seed 3  --save_results
python early_fusion.py --ss --modal t --pmode 2 --seed 3  --save_results
python early_fusion.py --ss --modal a --pmode 2 --seed 3  --save_results
python early_fusion.py --ss --modal v --pmode 2 --seed 3  --save_results
python early_fusion.py --ss --modal ta --pmode 2 --seed 3  --save_results
python early_fusion.py --ss --modal tv --pmode 2 --seed 3  --save_results
python early_fusion.py --ss --modal av --pmode 2 --seed 3  --save_results
python early_fusion.py --ss --modal tav --pmode 2 --seed 3  --save_results
python early_fusion.py --ss --modal t --pmode 3 --seed 3  --save_results
python early_fusion.py --ss --modal a --pmode 3 --seed 3  --save_results
python early_fusion.py --ss --modal v --pmode 3 --seed 3  --save_results
python early_fusion.py --ss --modal ta --pmode 3 --seed 3  --save_results
python early_fusion.py --ss --modal tv --pmode 3 --seed 3  --save_results
python early_fusion.py --ss --modal av --pmode 3 --seed 3  --save_results
python early_fusion.py --ss --modal tav --pmode 3 --seed 3  --save_results
python early_fusion.py --ss --modal t --pmode 4 --seed 3  --save_results
python early_fusion.py --ss --modal a --pmode 4 --seed 3  --save_results
python early_fusion.py --ss --modal v --pmode 4 --seed 3  --save_results
python early_fusion.py --ss --modal ta --pmode 4 --seed 3  --save_results
python early_fusion.py --ss --modal tv --pmode 4 --seed 3  --save_results
python early_fusion.py --ss --modal av --pmode 4 --seed 3  --save_results
python early_fusion.py --ss --modal tav --pmode 4 --seed 3  --save_results
python early_fusion.py --ss --modal t --pmode 5 --seed 3  --save_results
python early_fusion.py --ss --modal a --pmode 5 --seed 3  --save_results
python early_fusion.py --ss --modal v --pmode 5 --seed 3  --save_results
python early_fusion.py --ss --modal ta --pmode 5 --seed 3  --save_results
python early_fusion.py --ss --modal tv --pmode 5 --seed 3  --save_results
python early_fusion.py --ss --modal av --pmode 5 --seed 3  --save_results
python early_fusion.py --ss --modal tav --pmode 5 --seed 3  --save_results
python early_fusion.py --ss --modal t --pmode 6 --seed 3  --save_results
python early_fusion.py --ss --modal a --pmode 6 --seed 3  --save_results
python early_fusion.py --ss --modal v --pmode 6 --seed 3  --save_results
python early_fusion.py --ss --modal ta --pmode 6 --seed 3  --save_results
python early_fusion.py --ss --modal tv --pmode 6 --seed 3  --save_results
python early_fusion.py --ss --modal av --pmode 6 --seed 3  --save_results
python early_fusion.py --ss --modal tav --pmode 6 --seed 3  --save_results
python early_fusion.py --ss --modal t --pmode 7 --seed 3  --save_results
python early_fusion.py --ss --modal a --pmode 7 --seed 3  --save_results
python early_fusion.py --ss --modal v --pmode 7 --seed 3  --save_results
python early_fusion.py --ss --modal ta --pmode 7 --seed 3  --save_results
python early_fusion.py --ss --modal tv --pmode 7 --seed 3  --save_results
python early_fusion.py --ss --modal av --pmode 7 --seed 3  --save_results
python early_fusion.py --ss --modal tav --pmode 7 --seed 3  --save_results
python early_fusion.py --ss --modal t --pmode 8 --seed 3  --save_results
python early_fusion.py --ss --modal a --pmode 8 --seed 3  --save_results
python early_fusion.py --ss --modal v --pmode 8 --seed 3  --save_results
python early_fusion.py --ss --modal ta --pmode 8 --seed 3  --save_results
python early_fusion.py --ss --modal tv --pmode 8 --seed 3  --save_results
python early_fusion.py --ss --modal av --pmode 8 --seed 3  --save_results
python early_fusion.py --ss --modal tav --pmode 8 --seed 3  --save_results
python early_fusion.py --ss --modal t --pmode 0 --seed 4  --save_results
python early_fusion.py --ss --modal a --pmode 0 --seed 4  --save_results
python early_fusion.py --ss --modal v --pmode 0 --seed 4  --save_results
python early_fusion.py --ss --modal ta --pmode 0 --seed 4  --save_results
python early_fusion.py --ss --modal tv --pmode 0 --seed 4  --save_results
python early_fusion.py --ss --modal av --pmode 0 --seed 4  --save_results
python early_fusion.py --ss --modal tav --pmode 0 --seed 4  --save_results
python early_fusion.py --ss --modal t --pmode 1 --seed 4  --save_results
python early_fusion.py --ss --modal a --pmode 1 --seed 4  --save_results
python early_fusion.py --ss --modal v --pmode 1 --seed 4  --save_results
python early_fusion.py --ss --modal ta --pmode 1 --seed 4  --save_results
python early_fusion.py --ss --modal tv --pmode 1 --seed 4  --save_results
python early_fusion.py --ss --modal av --pmode 1 --seed 4  --save_results
python early_fusion.py --ss --modal tav --pmode 1 --seed 4  --save_results
python early_fusion.py --ss --modal t --pmode 2 --seed 4  --save_results
python early_fusion.py --ss --modal a --pmode 2 --seed 4  --save_results
python early_fusion.py --ss --modal v --pmode 2 --seed 4  --save_results
python early_fusion.py --ss --modal ta --pmode 2 --seed 4  --save_results
python early_fusion.py --ss --modal tv --pmode 2 --seed 4  --save_results
python early_fusion.py --ss --modal av --pmode 2 --seed 4  --save_results
python early_fusion.py --ss --modal tav --pmode 2 --seed 4  --save_results
python early_fusion.py --ss --modal t --pmode 3 --seed 4  --save_results
python early_fusion.py --ss --modal a --pmode 3 --seed 4  --save_results
python early_fusion.py --ss --modal v --pmode 3 --seed 4  --save_results
python early_fusion.py --ss --modal ta --pmode 3 --seed 4  --save_results
python early_fusion.py --ss --modal tv --pmode 3 --seed 4  --save_results
python early_fusion.py --ss --modal av --pmode 3 --seed 4  --save_results
python early_fusion.py --ss --modal tav --pmode 3 --seed 4  --save_results
python early_fusion.py --ss --modal t --pmode 4 --seed 4  --save_results
python early_fusion.py --ss --modal a --pmode 4 --seed 4  --save_results
python early_fusion.py --ss --modal v --pmode 4 --seed 4  --save_results
python early_fusion.py --ss --modal ta --pmode 4 --seed 4  --save_results
python early_fusion.py --ss --modal tv --pmode 4 --seed 4  --save_results
python early_fusion.py --ss --modal av --pmode 4 --seed 4  --save_results
python early_fusion.py --ss --modal tav --pmode 4 --seed 4  --save_results
python early_fusion.py --ss --modal t --pmode 5 --seed 4  --save_results
python early_fusion.py --ss --modal a --pmode 5 --seed 4  --save_results
python early_fusion.py --ss --modal v --pmode 5 --seed 4  --save_results
python early_fusion.py --ss --modal ta --pmode 5 --seed 4  --save_results
python early_fusion.py --ss --modal tv --pmode 5 --seed 4  --save_results
python early_fusion.py --ss --modal av --pmode 5 --seed 4  --save_results
python early_fusion.py --ss --modal tav --pmode 5 --seed 4  --save_results
python early_fusion.py --ss --modal t --pmode 6 --seed 4  --save_results
python early_fusion.py --ss --modal a --pmode 6 --seed 4  --save_results
python early_fusion.py --ss --modal v --pmode 6 --seed 4  --save_results
python early_fusion.py --ss --modal ta --pmode 6 --seed 4  --save_results
python early_fusion.py --ss --modal tv --pmode 6 --seed 4  --save_results
python early_fusion.py --ss --modal av --pmode 6 --seed 4  --save_results
python early_fusion.py --ss --modal tav --pmode 6 --seed 4  --save_results
python early_fusion.py --ss --modal t --pmode 7 --seed 4  --save_results
python early_fusion.py --ss --modal a --pmode 7 --seed 4  --save_results
python early_fusion.py --ss --modal v --pmode 7 --seed 4  --save_results
python early_fusion.py --ss --modal ta --pmode 7 --seed 4  --save_results
python early_fusion.py --ss --modal tv --pmode 7 --seed 4  --save_results
python early_fusion.py --ss --modal av --pmode 7 --seed 4  --save_results
python early_fusion.py --ss --modal tav --pmode 7 --seed 4  --save_results
python early_fusion.py --ss --modal t --pmode 8 --seed 4  --save_results
python early_fusion.py --ss --modal a --pmode 8 --seed 4  --save_results
python early_fusion.py --ss --modal v --pmode 8 --seed 4  --save_results
python early_fusion.py --ss --modal ta --pmode 8 --seed 4  --save_results
python early_fusion.py --ss --modal tv --pmode 8 --seed 4  --save_results
python early_fusion.py --ss --modal av --pmode 8 --seed 4  --save_results
python early_fusion.py --ss --modal tav --pmode 8 --seed 4  --save_results
