python mono_modal.py --ss --modal t --pmode 0 --save_results
python mono_modal.py --ss --modal a --pmode 0 --save_results
python mono_modal.py --ss --modal v --pmode 0 --save_results
python mono_modal.py --ss --modal t --pmode 1 --save_results
python mono_modal.py --ss --modal a --pmode 1 --save_results
python mono_modal.py --ss --modal v --pmode 1 --save_results
python mono_modal.py --ss --modal t --pmode 2 --save_results
python mono_modal.py --ss --modal a --pmode 2 --save_results
python mono_modal.py --ss --modal v --pmode 2 --save_results
python mono_modal.py --ss --modal t --pmode 3 --save_results
python mono_modal.py --ss --modal a --pmode 3 --save_results
python mono_modal.py --ss --modal v --pmode 3 --save_results
python mono_modal.py --ss --modal t --pmode 4 --save_results
python mono_modal.py --ss --modal a --pmode 4 --save_results
python mono_modal.py --ss --modal v --pmode 4 --save_results
python mono_modal.py --ss --modal t --pmode 5 --save_results
python mono_modal.py --ss --modal a --pmode 5 --save_results
python mono_modal.py --ss --modal v --pmode 5 --save_results
python mono_modal.py --ss --modal t --pmode 6 --save_results
python mono_modal.py --ss --modal a --pmode 6 --save_results
python mono_modal.py --ss --modal v --pmode 6 --save_results
python mono_modal.py --ss --modal t --pmode 7 --save_results
python mono_modal.py --ss --modal a --pmode 7 --save_results
python mono_modal.py --ss --modal v --pmode 7 --save_results
python mono_modal.py --ss --modal t --pmode 8 --save_results
python mono_modal.py --ss --modal a --pmode 8 --save_results
python mono_modal.py --ss --modal v --pmode 8 --save_results