python persona.py --wandb --batch_size 1
python persona.py --wandb --batch_size 2
python persona.py --wandb --batch_size 4
python persona.py --wandb --batch_size 8
python persona.py --wandb --batch_size 16
python persona.py --wandb --batch_size 1
python persona.py --wandb --batch_size 2
python persona.py --wandb --batch_size 4
python persona.py --wandb --batch_size 8
python persona.py --wandb --batch_size 16
python persona.py --wandb --batch_size 1
python persona.py --wandb --batch_size 2
python persona.py --wandb --batch_size 4
python persona.py --wandb --batch_size 8
python persona.py --wandb --batch_size 16
python persona.py --wandb --batch_size 1
python persona.py --wandb --batch_size 2
python persona.py --wandb --batch_size 4
python persona.py --wandb --batch_size 8
python persona.py --wandb --batch_size 16
python persona.py --wandb --batch_size 1
python persona.py --wandb --batch_size 2
python persona.py --wandb --batch_size 4
python persona.py --wandb --batch_size 8
python persona.py --wandb --batch_size 16